import type { Recommendation, RecommendationRule, SimulationContext } from '@/types/recommendationModel'

const STORAGE_KEY = 'i2sf_recommendations_v1'

function safeParse(raw: string): any {
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

function clamp(n: number, min: number, max: number) {
  return Math.max(min, Math.min(max, n))
}

function toDateOrUndef(v: any): Date | undefined {
  if (!v) return undefined
  const d = new Date(v)
  return Number.isNaN(d.getTime()) ? undefined : d
}

function hoursToTimeframe(hours: number) {
  if (hours <= 24) return 'Immediate'
  if (hours <= 24 * 7) return '1 week'
  if (hours <= 24 * 14) return '2 weeks'
  return '1 month'
}

function safeCapacity(building: any) {
  const totalCapacity = Number(building?.totalCapacity)
  if (Number.isFinite(totalCapacity) && totalCapacity > 0) return totalCapacity
  const rooms = Number(building?.totalRooms ?? 0)
  const fromRooms = rooms * 40
  if (Number.isFinite(fromRooms) && fromRooms > 0) return fromRooms
  return 1000
}

export class RecommendationEngine {
  private recommendations: Recommendation[] = []
  private rules: RecommendationRule[] = []
  private listeners: Set<(recommendations: Recommendation[]) => void> = new Set()

  constructor() {
    this.loadRecommendations()
    this.initializeRules()
  }

  private loadRecommendations(): void {
    const saved = localStorage.getItem(STORAGE_KEY)
    if (!saved) return
    const parsed = safeParse(saved)
    if (!Array.isArray(parsed)) return

    this.recommendations = parsed
      .map((r: any) => ({
        ...r,
        generatedAt: new Date(r.generatedAt),
        acceptedAt: toDateOrUndef(r.acceptedAt),
        dismissedAt: toDateOrUndef(r.dismissedAt),
      }))
      .filter((r: any) => r && r.id)
  }

  private saveRecommendations(): void {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(this.recommendations))
  }

  private ruleExistsWithinWindow(next: Recommendation, windowHours = 24) {
    const cutoff = Date.now() - windowHours * 60 * 60 * 1000
    return this.recommendations.some((r) => {
      if (r.status !== 'pending') return false
      if (r.category !== next.category) return false
      const overlap = r.affectedBuildings.some((b) => next.affectedBuildings.includes(b))
      if (!overlap) return false
      return new Date(r.generatedAt).getTime() >= cutoff
    })
  }

  private initializeRules(): void {
    this.rules.push({
      id: 'high-energy-load',
      weight: 9,
      condition: (ctx) =>
        Array.isArray(ctx.buildings) &&
        ctx.buildings.some((b: any) => {
          const base = Number(b.baseEnergyLoad ?? 0)
          const current = Number(b.currentEnergyLoad ?? b.baseEnergyLoad ?? 0)
          return base > 0 && current > base * 1.3
        }),
      generate: (ctx) => {
        const building = ctx.buildings.find((b: any) => {
          const base = Number(b.baseEnergyLoad ?? 0)
          const current = Number(b.currentEnergyLoad ?? b.baseEnergyLoad ?? 0)
          return base > 0 && current > base * 1.3
        }) as any

        const base = Number(building?.baseEnergyLoad ?? 0)
        const current = Number(building?.currentEnergyLoad ?? building?.baseEnergyLoad ?? 0)
        const excessPct = base > 0 ? ((current / base - 1) * 100) : 0

        return {
          id: `rec_${Date.now()}_energy`,
          title: `Reduce Energy Load in ${building?.buildingName ?? 'Building'}`,
          category: 'energy',
          severity: 'high',
          description: `${building?.buildingName ?? 'This building'} is consuming above baseline energy load.`,
          suggestedAction: 'Reduce AC usage during peak hours, shift non-essential lab sessions to evening, or enable energy-saving mode.',
          reasoning: [
            `Current load: ${current.toFixed(0)} kW`,
            `Baseline load: ${base.toFixed(0)} kW`,
            `Excess consumption: ${excessPct.toFixed(0)}%`,
            'Peak hours overlap with high HVAC demand',
          ],
          estimatedImpact: { metric: 'Energy Savings', improvement: 20, unit: '%' },
          affectedBuildings: building?.id ? [building.id] : [],
          implementation: { difficulty: 'easy', estimatedTime: 'Immediate', cost: 'none' },
          priority: 9,
          status: 'pending',
          generatedAt: new Date(),
          autoGenerated: true,
        }
      },
    })

    this.rules.push({
      id: 'critical-health',
      weight: 10,
      condition: (ctx) => Array.isArray(ctx.healthScores) && ctx.healthScores.some((h: any) => h.healthStatus === 'critical'),
      generate: (ctx) => {
        const critical = ctx.healthScores.find((h: any) => h.healthStatus === 'critical') as any
        return {
          id: `rec_${Date.now()}_health`,
          title: `Immediate Attention Required: ${critical?.buildingName ?? 'Building'}`,
          category: 'risk',
          severity: 'critical',
          description: `${critical?.buildingName ?? 'Building'} has a critical health score of ${Number(critical?.healthScore ?? 0).toFixed(0)}%.`,
          suggestedAction: 'Schedule emergency inspection, reduce occupancy by 20%, and initiate maintenance procedures.',
          reasoning: [
            `Health score: ${Number(critical?.healthScore ?? 0).toFixed(0)}%`,
            `Occupancy efficiency: ${Number(critical?.components?.occupancyEfficiency ?? 0).toFixed(0)}%`,
            `Energy efficiency: ${Number(critical?.components?.energyEfficiency ?? 0).toFixed(0)}%`,
            `Maintenance health: ${Number(critical?.components?.maintenanceHealth ?? 0).toFixed(0)}%`,
            'Score below critical threshold',
          ],
          estimatedImpact: { metric: 'Health Score Improvement', improvement: 15, unit: 'points' },
          affectedBuildings: critical?.buildingId ? [critical.buildingId] : [],
          implementation: { difficulty: 'complex', estimatedTime: '1-2 weeks', cost: 'high' },
          priority: 10,
          status: 'pending',
          generatedAt: new Date(),
          autoGenerated: true,
        }
      },
    })

    this.rules.push({
      id: 'occupancy-overflow',
      weight: 8,
      condition: (ctx) =>
        Array.isArray(ctx.buildings) &&
        ctx.buildings.some((b: any) => {
          const cap = safeCapacity(b)
          const occ = Number(b.currentOccupancy ?? 0)
          return cap > 0 && (occ / cap) * 100 > 90
        }),
      generate: (ctx) => {
        const overloaded = ctx.buildings.find((b: any) => {
          const cap = safeCapacity(b)
          const occ = Number(b.currentOccupancy ?? 0)
          return cap > 0 && (occ / cap) * 100 > 90
        }) as any

        const alternatives = ctx.buildings
          .filter((b: any) => {
            if (b.id === overloaded?.id) return false
            const cap = safeCapacity(b)
            const occ = Number(b.currentOccupancy ?? 0)
            return cap > 0 && (occ / cap) * 100 < 70
          })
          .slice(0, 1)

        const oCap = safeCapacity(overloaded)
        const oOcc = Number(overloaded?.currentOccupancy ?? 0)
        const oRate = oCap > 0 ? (oOcc / oCap) * 100 : 0

        const alt = alternatives[0]
        const aCap = safeCapacity(alt)
        const aOcc = Number(alt?.currentOccupancy ?? 0)
        const aRate = aCap > 0 ? (aOcc / aCap) * 100 : 0

        return {
          id: `rec_${Date.now()}_occupancy`,
          title: `Redistribute Load from ${overloaded?.buildingName ?? 'Building'}`,
          category: 'occupancy',
          severity: 'high',
          description: `${overloaded?.buildingName ?? 'Building'} is at ${oRate.toFixed(0)}% capacity.`,
          suggestedAction: alt?.id
            ? `Shift 2-3 sections to ${alt.buildingName} (currently at ${aRate.toFixed(0)}% capacity).`
            : 'Consider opening additional rooms or scheduling classes in shifts.',
          reasoning: [
            `Current occupancy: ${oOcc.toFixed(0)} / ${oCap.toFixed(0)}`,
            `Utilization: ${oRate.toFixed(0)}%`,
            'High stress on infrastructure',
            alt?.id ? `${alt.buildingName} has available capacity` : 'No immediate alternatives available',
          ],
          estimatedImpact: { metric: 'Stress Reduction', improvement: 25, unit: '%' },
          affectedBuildings: [overloaded?.id, alt?.id].filter(Boolean) as string[],
          implementation: { difficulty: 'medium', estimatedTime: '2-3 days', cost: 'low' },
          priority: 8,
          status: 'pending',
          generatedAt: new Date(),
          autoGenerated: true,
        }
      },
    })

    this.rules.push({
      id: 'grid-overload',
      weight: 9,
      condition: (ctx) => typeof ctx.gridStatus?.utilization === 'number' && ctx.gridStatus.utilization > 85,
      generate: (ctx) => {
        const grid = ctx.gridStatus
        const util = Number(grid?.utilization ?? 0)
        const highLoadBuildings = (ctx.buildings ?? [])
          .map((b: any) => ({ ...b, currentEnergyLoad: Number(b.currentEnergyLoad ?? b.baseEnergyLoad ?? 0) }))
          .filter((b: any) => b.currentEnergyLoad > 100)
          .sort((a: any, b: any) => b.currentEnergyLoad - a.currentEnergyLoad)
          .slice(0, 3)

        return {
          id: `rec_${Date.now()}_grid`,
          title: 'Implement Load Shedding Plan',
          category: 'grid',
          severity: util > 95 ? 'critical' : 'high',
          description: `Campus grid utilization at ${util.toFixed(0)}%. Approaching capacity limit.`,
          suggestedAction: `Reduce load in non-essential buildings: ${highLoadBuildings.map((b: any) => b.buildingName).filter(Boolean).join(', ') || 'selected blocks'}. Activate backup power if available.`,
          reasoning: [
            `Total load: ${Number(grid?.totalLoad ?? 0).toFixed(0)} / ${Number(grid?.totalCapacity ?? 0).toFixed(0)} kW`,
            `Utilization: ${util.toFixed(0)}%`,
            util > 95 ? 'CRITICAL: Risk of transformer trip' : 'WARNING: High utilization',
            highLoadBuildings.length
              ? `Top consumers: ${highLoadBuildings.map((b: any) => `${b.buildingName} (${Number(b.currentEnergyLoad ?? 0).toFixed(0)} kW)`).join(', ')}`
              : 'Top consumers: unavailable',
          ],
          estimatedImpact: { metric: 'Grid Utilization Reduction', improvement: 15, unit: '%' },
          affectedBuildings: highLoadBuildings.map((b: any) => b.id).filter(Boolean),
          implementation: { difficulty: 'easy', estimatedTime: 'Immediate', cost: 'none' },
          priority: util > 95 ? 10 : 9,
          status: 'pending',
          generatedAt: new Date(),
          autoGenerated: true,
        }
      },
    })

    this.rules.push({
      id: 'aging-infrastructure',
      weight: 7,
      condition: (ctx) => Array.isArray(ctx.agingData) && ctx.agingData.some((a: any) => Number(a.degradationFactor ?? 1) < 0.7),
      generate: (ctx) => {
        const aging = ctx.agingData.find((a: any) => Number(a.degradationFactor ?? 1) < 0.7) as any
        const building = (ctx.buildings ?? []).find((b: any) => b.id === aging?.buildingId) as any
        const deg = Number(aging?.degradationFactor ?? 1)
        const loss = Number(aging?.efficiencyLoss ?? 0)
        const age = Number(aging?.currentAge ?? 0)
        return {
          id: `rec_${Date.now()}_aging`,
          title: `Schedule Renovation for ${building?.buildingName ?? 'Building'}`,
          category: 'maintenance',
          severity: deg < 0.6 ? 'high' : 'medium',
          description: `Building condition at ${(deg * 100).toFixed(0)}%. Significant degradation detected.`,
          suggestedAction: 'Schedule major renovation including HVAC upgrade, electrical system inspection, and structural repairs.',
          reasoning: [
            `Building age: ${age.toFixed(0)} years`,
            `Degradation factor: ${(deg * 100).toFixed(0)}%`,
            `Efficiency loss: ${loss.toFixed(0)}%`,
          ],
          estimatedImpact: { metric: 'Efficiency Restoration', improvement: clamp(loss, 5, 40), unit: '%' },
          affectedBuildings: aging?.buildingId ? [aging.buildingId] : [],
          implementation: { difficulty: 'complex', estimatedTime: '2-3 months', cost: 'high' },
          priority: deg < 0.6 ? 8 : 7,
          status: 'pending',
          generatedAt: new Date(),
          autoGenerated: true,
        }
      },
    })

    this.rules.push({
      id: 'predictive-maintenance',
      weight: 8,
      condition: (ctx) => Array.isArray(ctx.maintenanceRecords) && ctx.maintenanceRecords.some((m: any) => !!m.predictedReason && Number(m.confidence ?? 0) > 70 && m.status === 'pending'),
      generate: (ctx) => {
        const prediction = ctx.maintenanceRecords.find((m: any) => !!m.predictedReason && Number(m.confidence ?? 0) > 70 && m.status === 'pending') as any
        const building = (ctx.buildings ?? []).find((b: any) => b.id === prediction?.buildingId) as any

        const pr = String(prediction?.priority ?? 'high')
        const hours = pr === 'critical' ? 24 * 3 : pr === 'high' ? 24 * 7 : pr === 'medium' ? 24 * 14 : 24 * 30

        return {
          id: `rec_${Date.now()}_predictive`,
          title: `Preventive Maintenance Alert: ${building?.buildingName ?? 'Building'}`,
          category: 'maintenance',
          severity: pr === 'critical' ? 'critical' : 'high',
          description: `Predictive signal indicates maintenance need with ${Number(prediction?.confidence ?? 0).toFixed(0)}% confidence.`,
          suggestedAction: `Schedule preventive maintenance within ${hoursToTimeframe(hours)}. Priority: ${pr}.`,
          reasoning: [String(prediction?.predictedReason ?? 'Predictive signal detected')],
          estimatedImpact: { metric: 'Failure Prevention', improvement: 85, unit: '%' },
          affectedBuildings: prediction?.buildingId ? [prediction.buildingId] : [],
          implementation: { difficulty: 'medium', estimatedTime: hoursToTimeframe(hours), cost: 'medium' },
          priority: pr === 'critical' ? 9 : 8,
          status: 'pending',
          generatedAt: new Date(),
          autoGenerated: true,
        }
      },
    })

    this.rules.push({
      id: 'event-optimization',
      weight: 6,
      condition: (ctx) => Array.isArray(ctx.events) && ctx.events.some((e: any) => e.active && (e.impact === 'high' || e.impact === 'critical') && Number(e.loadMultipliers?.energy ?? 1) > 1.3),
      generate: (ctx) => {
        const event = ctx.events.find((e: any) => e.active && (e.impact === 'high' || e.impact === 'critical') && Number(e.loadMultipliers?.energy ?? 1) > 1.3) as any
        const mult = Number(event?.loadMultipliers?.energy ?? 1)

        return {
          id: `rec_${Date.now()}_event`,
          title: `Optimize Load During ${event?.name ?? 'Event'}`,
          category: 'optimization',
          severity: 'medium',
          description: `Event will increase energy load by ${((mult - 1) * 100).toFixed(0)}%.`,
          suggestedAction: 'Pre-cool affected buildings 1 hour before event. Reduce non-essential loads. Ensure backup power is on standby.',
          reasoning: [
            `Event: ${event?.name ?? 'Event'}`,
            `Expected attendance: ${Number(event?.expectedAttendance ?? 0).toFixed(0)}`,
            `Energy multiplier: ${mult.toFixed(2)}x`,
          ],
          estimatedImpact: { metric: 'Peak Load Reduction', improvement: 12, unit: '%' },
          affectedBuildings: Array.isArray(event?.buildingsAffected) ? event.buildingsAffected : [],
          implementation: { difficulty: 'easy', estimatedTime: '1 day preparation', cost: 'low' },
          priority: 6,
          status: 'pending',
          generatedAt: new Date(),
          autoGenerated: true,
        }
      },
    })
  }

  public analyzeAndGenerate(context: SimulationContext): Recommendation[] {
    const newRecommendations: Recommendation[] = []

    for (const rule of this.rules) {
      try {
        if (!rule.condition(context)) continue
        const rec = rule.generate(context)
        if (!rec.affectedBuildings.length) continue
        if (this.ruleExistsWithinWindow(rec, 24)) continue
        newRecommendations.push(rec)
      } catch {
      }
    }

    if (newRecommendations.length) {
      this.recommendations.push(...newRecommendations)
      this.saveRecommendations()
      this.notifyListeners()
    }

    return newRecommendations
  }

  public getPendingRecommendations(): Recommendation[] {
    return this.recommendations
      .filter((r) => r.status === 'pending')
      .sort((a, b) => b.priority - a.priority)
  }

  public getAllRecommendations(): Recommendation[] {
    return [...this.recommendations].sort((a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime())
  }

  public acceptRecommendation(id: string): void {
    const rec = this.recommendations.find((r) => r.id === id)
    if (!rec) return
    rec.status = 'accepted'
    rec.acceptedAt = new Date()
    this.saveRecommendations()
    this.notifyListeners()
  }

  public dismissRecommendation(id: string, reason: string): void {
    const rec = this.recommendations.find((r) => r.id === id)
    if (!rec) return
    rec.status = 'dismissed'
    rec.dismissedAt = new Date()
    rec.dismissalReason = reason
    this.saveRecommendations()
    this.notifyListeners()
  }

  public markImplemented(id: string): void {
    const rec = this.recommendations.find((r) => r.id === id)
    if (!rec) return
    rec.status = 'implemented'
    this.saveRecommendations()
    this.notifyListeners()
  }

  public clearAll(): void {
    this.recommendations = []
    this.saveRecommendations()
    this.notifyListeners()
  }

  public subscribe(listener: (recommendations: Recommendation[]) => void): () => void {
    this.listeners.add(listener)
    listener(this.getPendingRecommendations())
    return () => this.listeners.delete(listener)
  }

  private notifyListeners(): void {
    const next = this.getPendingRecommendations()
    this.listeners.forEach((l) => l(next))
  }
}

export const recommendationEngine = new RecommendationEngine()
