export type RecommendationCategory = 'energy' | 'occupancy' | 'maintenance' | 'risk' | 'grid' | 'optimization'

export type RecommendationSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info'

export type RecommendationStatus = 'pending' | 'accepted' | 'dismissed' | 'implemented'

export interface Recommendation {
  id: string
  title: string
  category: RecommendationCategory
  severity: RecommendationSeverity
  description: string
  suggestedAction: string
  reasoning: string[]
  estimatedImpact: {
    metric: string
    improvement: number
    unit: string
  }
  affectedBuildings: string[]
  implementation: {
    difficulty: 'easy' | 'medium' | 'complex'
    estimatedTime: string
    cost: 'low' | 'medium' | 'high' | 'none'
  }
  priority: number
  status: RecommendationStatus
  generatedAt: Date
  acceptedAt?: Date
  dismissedAt?: Date
  dismissalReason?: string
  autoGenerated: boolean
}

export interface SimulationContext {
  buildings: any[]
  simulations: any[]
  healthScores: any[]
  gridStatus: any
  events: any[]
  agingData: any[]
  maintenanceRecords: any[]
  occupancyRecords: any[]
}

export interface RecommendationRule {
  id: string
  weight: number
  condition: (context: SimulationContext) => boolean
  generate: (context: SimulationContext) => Recommendation
}
